version: '3.9'
services:
  #Servicio para NodeJS
  t2-content:
    container_name: t2-content
    build: . 
    ports:
      - 3002:3002  # Adjust the ports as needed
    links:
      - t2-content-db
    depends_on:
      - t2-content-db
      - rabbitmq
    networks:
      - taller2    

  # Servicio para PostgreSQL
  t2-content-db:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.db
    container_name: t2-content-db
    restart: always
    environment:
      POSTGRES_DB: content
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5434:5434
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - taller2  

  # Servicio para PgAdmin
  t2-content-pgadmin:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.pgadmin
    container_name: t2-content-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5054:80
    depends_on:
      - t2-content-db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - taller2
  
  t2-content-prisma:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: t2-content-prisma
    depends_on:
      - t2-content
      - t2-content-db
    ports:
      - "5055:5055"
    entrypoint: ["bash", "-c", "npx prisma migrate dev --name init"]
    restart: "no"
    networks:
      - taller2  

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - taller2

volumes:    
  postgres-data:
  pgadmin-data:

networks:
  taller2:
    external: true